export type Lang = "en" | "id";

export const content = {
  en: {
    nav: {
      logo: "~/alvacodee",
      about: "About",
      projects: "Projects",
      experience: "Experience",
      writing: "Writing",
      journey: "Journey",
      contact: "Contact",
      resume: "Resume",
    },
    hero: {
      status: "Open to opportunities",
      name: "Zahran Alvan.",
      role: "Software Engineering · DevOps · SRE · AI/ML",
      roleTags: ["Software Engineering", "DevOps", "SRE", "AI/ML"],
      bio1: `I'm a Computer Science student at <strong>Institut Teknologi Bandung</strong>, fascinated by the intersection of <strong>Data, AI, and elegant software architecture</strong>.`,
      bio2: `I believe powerful AI deserves a robust foundation. My current focus is mastering Software Engineering fundamentals — from system design to production-ready code — so that intelligent models live inside systems that are not just smart, but truly reliable.`,
      bio3: `When I'm not building, you'll find me competing in data competitions, writing about what I find interesting, or exploring ideas at the edge of what I know.`,
      downloadCV: "Download CV",
      stats: [
        { value: "8+", label: "Projects" },
        { value: "3+", label: "Competitions" },
        { value: "2", label: "Papers" },
        { value: "4th", label: "Semester" },
      ],
    },
    sections: {
      projects: "Projects",
      experience: "Experience",
      education: "Education",
      writing: "Writing",
      skills: "Skills",
      achievements: "Achievements",
    },
    projects: [
      {
        title: "Alvacodee Web",
        sub: "Portfolio Website",
        tech: ["Next.js", "TypeScript", "Tailwind", "Gemini API"],
        desc: "Portfolio site with embedded Gemini AI chatbot via Next.js serverless API.",
        link: "https://github.com/Alvacodee/Alvacodee-Web",
      },
      {
        title: "DUITKUDW",
        sub: "Finance Tracker App",
        tech: ["Go", "React.js", "Python", "PostgreSQL", "Docker"],
        desc: "Finance tracker with hybrid ML expense forecasting (Weighted Linear Regression + Holt-Winters).",
        link: "https://github.com/Alvacodee/DUITKUDW",
      },
      {
        title: "SehatSehatKuatKuat",
        sub: "DOM/CSS Traversal Engine",
        tech: ["Go", "Next.js", "TypeScript", "Tailwind", "Docker"],
        desc: "DOM/CSS traversal engine with BFS/DFS visualization and parallel goroutine worker pools.",
        link: "https://github.com/Alvacodee/SehatSehatKuatKuat",
      },
      {
        title: "EigenPustaka",
        sub: "Digital E-library Platform",
        tech: ["React.js", "Vite", "Tailwind CSS", "Python"],
        desc: "Digital e-library platform with recommendation engine and a clean reading experience.",
        link: "https://github.com/Alvacodee/EigenPustaka",
      },
      {
        title: "EduHub",
        sub: "Desktop LMS",
        tech: ["Java", "JavaFX", "SQLite", "Maven"],
        desc: "Desktop LMS for teachers & students — quiz, forum, leaderboard across 12 DB tables.",
        link: "https://github.com/Alvacodee/EduHub",
      },
    ],
    experience: [
      {
        title: "Google Developer Student Clubs ITB",
        sub: "Explorer · AI Path",
        date: "Apr 2025 – Present",
        tag: "Community",
        desc: "Completed an intensive curriculum from Intro to AI and Python through From NLP to LLM, applying hands-on ML and deep learning projects.",
      },
      {
        title: "Wisuda Oktober HMIF ITB 2025",
        sub: "Staff · Sponsorship Division",
        date: "Sep 2025 – Oct 2025",
        tag: "Organization",
        desc: "Managed a database of 50+ potential sponsors. Coordinated with external stakeholders and executed strategic outreach to 50+ corporate partners and startups.",
      },
      {
        title: "Asrama ITB Jatinangor",
        sub: "Tutor · Discipline & Environmental Health",
        date: "Jul 2025 – Present",
        tag: "Volunteer",
        desc: "Managed cleanliness and orderliness for 100+ dormitory residents. Organized regular health and hygiene campaigns.",
      },
    ],
    education: [
      {
        title: "Institut Teknologi Bandung",
        sub: "Bachelor of Computer Science",
        date: "2024 – Present",
        desc: "Currently in 4th semester. Courses: OOP, Algorithm Strategy, Formal Language Theory & Automata, Computer Network, Database, Project Management.",
      },
      {
        title: "SMAN 2 Nganjuk",
        sub: "Senior High School",
        date: "2020 – 2023",
        desc: "Mathematics and Natural Science major.",
      },
      {
        title: "SMPN 1 Nganjuk",
        sub: "Junior High School",
        date: "2017 – 2020",
        desc: "General Studies.",
      },
    ],
    writing: [
      {
        title: "Pemetaan Jaringan Blockchain Sebagai Graf Terhubung",
        sub: "Analisis Diameter, Clustering, dan Kerentanannya",
        platform: "Discrete Mathematics · ITB",
        date: "June 2025",
        desc: "Models peer connectivity in blockchain systems using graph theory, analyzing diameter, degree distribution, and clustering coefficient to evaluate network robustness.",
        link: "https://informatika.stei.itb.ac.id/~rinaldi.munir/Matdis/2024-2025-2/Makalah2025/Makalah-Matdis-2025-IF-ITB%20(123).pdf",
      },
      {
        title: "Comparative Analysis of Face Recognition",
        sub: "Eigenfaces (PCA) vs Fisherfaces (LDA)",
        platform: "Linear Algebra · GitHub",
        date: "Dec 2025",
        desc: "Comparative study of accuracy trade-offs between PCA-based Eigenfaces and LDA-based Fisherfaces under varying facial expressions and illumination conditions.",
        link: "https://github.com/Alvacodee/PCA-Vs-LDA/blob/main/doc/13524124_Zahran-Alvan-P-W.pdf",
      },
      {
        title: "Dari Mimpi Kecil Hingga Gerbang ITB",
        sub: "Perjalanan Panjang Menuju Awal Lembaran Baru",
        platform: "Medium · Personal",
        date: "Sep 2025",
        desc: "Personal journey from a small-town dreamer to an ITB student — the challenges, the long road, and the new beginning.",
        link: "https://medium.com/@zahranalvan2901/dari-mimpi-kecil-hingga-gerbang-itb-perjalanan-panjang-menuju-awal-lembaran-baru-072bddd599de",
      },
    ],
    skills: {
      "Programming Languages": ["Python", "C/C++", "Java", "JavaScript", "TypeScript", "Haskell", "Prolog"],
      "Machine Learning & Data Science": ["Pandas", "NumPy", "Scikit-Learn", "TensorFlow", "Keras", "OpenCV", "XGBoost", "LightGBM", "CatBoost", "Matplotlib", "Seaborn", "SciPy"],
      "Web & Backend": ["React", "Next.js", "Tailwind CSS", "FastAPI", "Go"],
      "Infrastructure & Tools": ["Docker", "PostgreSQL", "SQLite", "Git", "Linux"],
    },
    achievements: [
      {
        title: "GDGoC ITB-X Final Leaderboard",
        sub: "3rd Place",
        date: "2025",
        tag: "Competition",
        desc: "Solved real-world data problems involving data preprocessing, cleaning, visualization, and machine learning approaches.",
      },
    ],
    contact: {
      heading: "Let's talk.",
      sub: "Have a project in mind, want to collaborate, or just want to geek out about Data and AI? I'm always open to new conversations.",
      email: "Email",
      github: "GitHub",
      linkedin: "LinkedIn",
      labelEmail: "Your email",
      labelSubject: "Subject",
      labelMessage: "Message",
      placeholderEmail: "your@email.com",
      placeholderSubject: "Collaboration / Opportunity / Just saying hi",
      placeholderMessage: "Hi Zahran, I'd like to...",
      send: "Send message",
      sending: "Sending...",
      successTitle: "Message sent!",
      successSub: "Thanks for reaching out. I'll get back to you as soon as possible.",
      another: "Send another message",
    },
    footer: {
      copy: "Zahran Alvan Putra Winarko",
      madeWith: "Built with Next.js & Tailwind",
    },
  },

  // ===================== INDONESIAN =====================
  id: {
    nav: {
      logo: "~/alvacodee",
      about: "Tentang",
      projects: "Proyek",
      experience: "Pengalaman",
      writing: "Tulisan",
      journey: "Perjalanan",
      contact: "Kontak",
      resume: "Resume",
    },
    hero: {
      status: "Terbuka untuk peluang",
      name: "Zahran Alvan.",
      role: "Software Engineering · DevOps · SRE · AI/ML",
      roleTags: ["Software Engineering", "DevOps", "SRE", "AI/ML"],
      bio1: `Saya mahasiswa Ilmu Komputer di <strong>Institut Teknologi Bandung</strong>, terpesona oleh persimpangan antara <strong>Data, AI, dan arsitektur perangkat lunak yang elegan</strong>.`,
      bio2: `Saya percaya AI yang powerful butuh fondasi yang kokoh. Fokus saya saat ini adalah menguasai fundamental Software Engineering — dari desain sistem hingga kode siap produksi — agar model AI cerdas bisa hidup dalam sistem yang tidak hanya pintar, tapi benar-benar andal.`,
      bio3: `Saat tidak sedang membangun sesuatu, kamu bisa menemukan saya sedang ikut kompetisi data, menulis tentang hal yang menarik, atau mengeksplorasi ide-ide di tepi dari apa yang saya ketahui.`,
      downloadCV: "Unduh CV",
      stats: [
        { value: "8+", label: "Proyek" },
        { value: "3+", label: "Kompetisi" },
        { value: "2", label: "Makalah" },
        { value: "4", label: "Semester" },
      ],
    },
    sections: {
      projects: "Proyek",
      experience: "Pengalaman",
      education: "Pendidikan",
      writing: "Tulisan",
      skills: "Keahlian",
      achievements: "Prestasi",
    },
    projects: [
      {
        title: "Alvacodee Web",
        sub: "Website Portfolio",
        tech: ["Next.js", "TypeScript", "Tailwind", "Gemini API"],
        desc: "Website portfolio dengan AI chatbot Gemini tertanam via Next.js serverless API.",
        link: "https://github.com/Alvacodee/Alvacodee-Web",
      },
      {
        title: "DUITKUDW",
        sub: "Aplikasi Pencatat Keuangan",
        tech: ["Go", "React.js", "Python", "PostgreSQL", "Docker"],
        desc: "Pencatat keuangan dengan prediksi pengeluaran ML hibrida (Weighted Linear Regression + Holt-Winters).",
        link: "https://github.com/Alvacodee/DUITKUDW",
      },
      {
        title: "SehatSehatKuatKuat",
        sub: "Engine Traversal DOM/CSS",
        tech: ["Go", "Next.js", "TypeScript", "Tailwind", "Docker"],
        desc: "Engine traversal DOM/CSS dengan visualisasi BFS/DFS dan goroutine worker pool paralel.",
        link: "https://github.com/Alvacodee/SehatSehatKuatKuat",
      },
      {
        title: "EigenPustaka",
        sub: "Platform E-library Digital",
        tech: ["React.js", "Vite", "Tailwind CSS", "Python"],
        desc: "Platform e-library digital dengan mesin rekomendasi dan pengalaman membaca yang nyaman.",
        link: "https://github.com/Alvacodee/EigenPustaka",
      },
      {
        title: "EduHub",
        sub: "LMS Desktop",
        tech: ["Java", "JavaFX", "SQLite", "Maven"],
        desc: "LMS desktop untuk guru & siswa — kuis, forum, leaderboard dengan 12 tabel database.",
        link: "https://github.com/Alvacodee/EduHub",
      },
    ],
    experience: [
      {
        title: "Google Developer Student Clubs ITB",
        sub: "Explorer · Jalur AI",
        date: "Apr 2025 – Sekarang",
        tag: "Komunitas",
        desc: "Menyelesaikan kurikulum intensif dari Intro to AI dan Python hingga From NLP to LLM, dengan proyek ML dan deep learning secara hands-on.",
      },
      {
        title: "Wisuda Oktober HMIF ITB 2025",
        sub: "Staf · Divisi Sponsorship",
        date: "Sep 2025 – Okt 2025",
        tag: "Organisasi",
        desc: "Mengelola database 50+ calon sponsor. Berkoordinasi dengan pemangku kepentingan eksternal dan melakukan outreach strategis ke 50+ mitra korporat dan startup.",
      },
      {
        title: "Asrama ITB Jatinangor",
        sub: "Tutor · Disiplin & Kebersihan Lingkungan",
        date: "Jul 2025 – Sekarang",
        tag: "Sukarela",
        desc: "Mengelola kebersihan dan ketertiban untuk 100+ penghuni asrama. Mengorganisir kampanye kesehatan dan kebersihan secara rutin.",
      },
    ],
    education: [
      {
        title: "Institut Teknologi Bandung",
        sub: "S1 Ilmu Komputer / Teknik Informatika",
        date: "2024 – Sekarang",
        desc: "Sedang menjalani semester 4. Mata kuliah: OOP, Strategi Algoritma, Bahasa Formal & Automata, Jaringan Komputer, Basis Data, Manajemen Proyek.",
      },
      {
        title: "SMAN 2 Nganjuk",
        sub: "SMA Alumni",
        date: "2020 – 2023",
        desc: "Jurusan Matematika dan Ilmu Pengetahuan Alam.",
      },
      {
        title: "SMPN 1 Nganjuk",
        sub: "SMP Alumni",
        date: "2017 – 2020",
        desc: "Studi Umum.",
      },
    ],
    writing: [
      {
        title: "Pemetaan Jaringan Blockchain Sebagai Graf Terhubung",
        sub: "Analisis Diameter, Clustering, dan Kerentanannya",
        platform: "Matematika Diskret · ITB",
        date: "Juni 2025",
        desc: "Memodelkan konektivitas peer dalam sistem blockchain menggunakan teori graf, menganalisis diameter, distribusi derajat, dan koefisien clustering untuk mengevaluasi ketahanan jaringan.",
        link: "https://informatika.stei.itb.ac.id/~rinaldi.munir/Matdis/2024-2025-2/Makalah2025/Makalah-Matdis-2025-IF-ITB%20(123).pdf",
      },
      {
        title: "Analisis Komparatif Face Recognition",
        sub: "Eigenfaces (PCA) vs Fisherfaces (LDA)",
        platform: "Aljabar Linear · GitHub",
        date: "Des 2025",
        desc: "Studi komparatif trade-off akurasi antara Eigenfaces berbasis PCA dan Fisherfaces berbasis LDA pada variasi ekspresi wajah dan kondisi pencahayaan.",
        link: "https://github.com/Alvacodee/PCA-Vs-LDA/blob/main/doc/13524124_Zahran-Alvan-P-W.pdf",
      },
      {
        title: "Dari Mimpi Kecil Hingga Gerbang ITB",
        sub: "Perjalanan Panjang Menuju Awal Lembaran Baru",
        platform: "Medium · Personal",
        date: "Sep 2025",
        desc: "Perjalanan pribadi dari seorang pemimpi di kota kecil hingga menjadi mahasiswa ITB — tantangan, jalan panjang, dan awal yang baru.",
        link: "https://medium.com/@zahranalvan2901/dari-mimpi-kecil-hingga-gerbang-itb-perjalanan-panjang-menuju-awal-lembaran-baru-072bddd599de",
      },
    ],
    skills: {
      "Bahasa Pemrograman": ["Python", "C/C++", "Java", "JavaScript", "TypeScript", "Haskell", "Prolog"],
      "Machine Learning & Data Science": ["Pandas", "NumPy", "Scikit-Learn", "TensorFlow", "Keras", "OpenCV", "XGBoost", "LightGBM", "CatBoost", "Matplotlib", "Seaborn", "SciPy"],
      "Web & Backend": ["React", "Next.js", "Tailwind CSS", "FastAPI", "Go"],
      "Infrastruktur & Tools": ["Docker", "PostgreSQL", "SQLite", "Git", "Linux"],
    },
    achievements: [
      {
        title: "GDGoC ITB-X Final Leaderboard",
        sub: "Juara 3",
        date: "2025",
        tag: "Kompetisi",
        desc: "Menyelesaikan permasalahan data nyata meliputi preprocessing, pembersihan, visualisasi data, dan pendekatan machine learning.",
      },
    ],
    contact: {
      heading: "Mari berbicara.",
      sub: "Ada proyek di benak kamu, ingin berkolaborasi, atau sekadar ngobrol tentang Data dan AI? Saya selalu terbuka untuk percakapan baru.",
      email: "Email",
      github: "GitHub",
      linkedin: "LinkedIn",
      labelEmail: "Email kamu",
      labelSubject: "Subjek",
      labelMessage: "Pesan",
      placeholderEmail: "email@kamu.com",
      placeholderSubject: "Kolaborasi / Peluang / Sekadar sapa",
      placeholderMessage: "Halo Zahran, saya ingin...",
      send: "Kirim pesan",
      sending: "Mengirim...",
      successTitle: "Pesan terkirim!",
      successSub: "Terima kasih sudah menghubungi. Saya akan membalas sesegera mungkin.",
      another: "Kirim pesan lain",
    },
    footer: {
      copy: "Zahran Alvan Putra Winarko",
      madeWith: "Dibangun dengan Next.js & Tailwind",
    },
  },
};
